import Navbar from "@/components/navbar/Navbar";
import SmoothScrollProvider from "@/lib/providers/SmoothScroll";
import ThemeProvider from "@/lib/providers/ThemeProvider";
import type { LocaleLayoutProps } from "@/lib/types/types";
import type { Metadata } from "next";
import { NextIntlClientProvider, useLocale, useMessages } from "next-intl";
import { notFound } from "next/navigation";

export async function generateStaticParams() {
  return [{ lang: "ar" }, { lang: "en" }, { lang: "fr" }];
}

export const metadata: Metadata = {
  title: "Starter Kit",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: LocaleLayoutProps) {
  const messages = useMessages();

  const dir = locale === "ar" ? "rtl" : "ltr";

  const nextLocale = useLocale();

  if (nextLocale !== locale) notFound();

  return (
    <>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <ThemeProvider>
          <SmoothScrollProvider>
            <main dir={dir}>
              <Navbar />
              {children}
            </main>
          </SmoothScrollProvider>
        </ThemeProvider>
      </NextIntlClientProvider>
    </>
  );
}
